// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotnet_store.Models;

#nullable disable

namespace dotnet_store.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250520150604_AddFurnitureProducts2")]
    partial class AddFurnitureProducts2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("dotnet_store.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Koltuk"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Masa"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sandalye"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Sehpa"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Dolap"
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Minimalist tarzda, rahat oturumlu 3 kişilik koltuk.",
                            ImageUrl = "/images/koltuk.jpg",
                            Name = "İskandinav Koltuk",
                            Price = 1000.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Description = "Masif meşe ağacından üretilmiş 6 kişilik yemek masası.",
                            ImageUrl = "/images/masa.jpg",
                            Name = "Doğal Ahşap Masa",
                            Price = 1000.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Description = "Ergonomik oturumlu, modern tarzda sandalye.",
                            ImageUrl = "/images/sandalye.jpg",
                            Name = "Yemek Sandalyesi",
                            Price = 800.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4,
                            Description = "Orta sehpa olarak kullanılabilecek modern yuvarlak sehpa.",
                            ImageUrl = "/images/sehpa.jpg",
                            Name = "Yuvarlak Sehpa",
                            Price = 700.0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 5,
                            Description = "Küçük alanlar için ideal, sade tasarımlı dolap.",
                            ImageUrl = "/images/dolap.jpg",
                            Name = "Minimal Dolap",
                            Price = 1200.0
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Slider", b =>
                {
                    b.Property<int>("SliderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("SliderId");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            SliderId = 1,
                            Description = "Evini yenilemek için ilham verici mobilyalar",
                            DisplayIndex = 0,
                            ImageUrl = "/images/slider1.jpg",
                            IsActive = true,
                            Title = "Modern Yaşam Alanları"
                        },
                        new
                        {
                            SliderId = 2,
                            Description = "En çok tercih edilen koltuk ve masa takımları burada",
                            DisplayIndex = 1,
                            ImageUrl = "/images/slider2.jpg",
                            IsActive = true,
                            Title = "Konfor & Şıklık"
                        });
                });

            modelBuilder.Entity("dotnet_store.Models.Product", b =>
                {
                    b.HasOne("dotnet_store.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("dotnet_store.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
